# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 bet3rd

"""Steam integration ports used by domain login services."""

from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Any, Protocol


class SteamProcessPort(Protocol):
    def install_path(self) -> str | None: ...
    def local_vdf_path(self) -> str: ...
    def kill(self, *, timeout: float = 10.0) -> None: ...
    def launch(self, *, open_cs2: bool = False) -> None: ...
    def launch_with_spoofer(self, injector_path: str, *, open_cs2: bool = False) -> None: ...


class VdfFilePort(Protocol):
    def read_vdf(self, path: str) -> dict[str, Any]: ...
    def write_vdf(self, path: str, data: dict[str, Any]) -> None: ...
    def read_text(self, path: str) -> str: ...
    def write_text(self, path: str, text: str) -> None: ...


class FileGuardPort(Protocol):
    def protect(self, *paths: str) -> AbstractContextManager[None]: ...


class SteamCryptoPort(Protocol):
    def crc32_key(self, username: str) -> str: ...
    def encrypt(self, token: str, username: str) -> str: ...
    def decrypt(self, encrypted: str, username: str) -> str: ...


class SteamRegistryPort(Protocol):
    def set_autologin_with_remember(self, username: str) -> None: ...


class PersonaPort(Protocol):
    def set_state(self, steam_dir: str, steam_id: str, state: int) -> None: ...
    def set_remote_play(self, steam_dir: str, steam_id: str, enabled: bool) -> None: ...
    def set_cs2_launch_options(self, steam_dir: str, steam_id: str, options: str) -> None: ...
